### ISSUE TITLE
Build fails with error: no member named 'flatbuffer_version_string' in namespace 'flatbuffers'

### ISSUE THREAD

**Issue by alebcay** [snort3/snort3#235]
Hi 👋  I'm working on packaging Snort 3.1.24.0 for [Homebrew](https://brew.sh) and we noticed that it fails to build with `flatbuffers` 2.0.6. The full error is:
```
  [ 95%] Building CXX object tools/snort2lua/preprocessor_states/CMakeFiles/preprocessor_states.dir/pps_dns.cc.o
  cd /tmp/snort-20220305-79651-1o0h3ri/snort3-3.1.24.0/build/tools/snort2lua/preprocessor_states && /opt/homebrew/Library/Homebrew/shims/mac/super/clang++ -DHAVE_CONFIG_H -Dinline=inline -Drestrict=__restrict -I/tmp/snort-20220305-79651-1o0h3ri/snort3-3.1.24.0/build -I/tmp/snort-20220305-79651-1o0h3ri/snort3-3.1.24.0 -I/tmp/snort-20220305-79651-1o0h3ri/snort3-3.1.24.0/tools/snort2lua -fvisibility=hidden   -DNDEBUG -g -ggdb  -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free  -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -std=c++14 -MD -MT tools/snort2lua/preprocessor_states/CMakeFiles/preprocessor_states.dir/pps_dns.cc.o -MF CMakeFiles/preprocessor_states.dir/pps_dns.cc.o.d -o CMakeFiles/preprocessor_states.dir/pps_dns.cc.o -c /tmp/snort-20220305-79651-1o0h3ri/snort3-3.1.24.0/tools/snort2lua/preprocessor_states/pps_dns.cc
  /tmp/snort-20220305-79651-1o0h3ri/snort3-3.1.24.0/src/utils/util.cc:119:54: error: no member named 'flatbuffer_version_string' in namespace 'flatbuffers'; did you mean 'flatbuffers_version_string'?
      LogMessage("           Using %s\n", flatbuffers::flatbuffer_version_string);
                                          ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                                                       flatbuffers_version_string
```

We believe the issue is caused by Flatbuffers renaming that function to `flatbuffers_version_string` instead, which occurred in https://github.com/google/flatbuffers/commit/7089c9ecddb5e8fba49b875f871cf27e3a31d13f (included in 2.0.6). The easiest fix would be just to rename the usage of it here, but then it would break on older versions of Flatbuffers. So, maybe some extra conditional logic/check is needed here.

For reference, the downstream issue at Homebrew is https://github.com/Homebrew/homebrew-core/pull/96364. Thanks!

**Comment by InverseRE** [comment]
Fixed in 3ec185030ef871dbe4a1df997b5880c098aa7101
@alebcay thanks for reporting the issue.
