### ISSUE TITLE
Replace usage of `std::ptr_fun` which is officially removed in C++17

### ISSUE THREAD

**Issue by cho-m** [snort3/snort3#347]
When updating Homebrew formula to 3.1.81.0 (https://github.com/Homebrew/homebrew-core/pull/163433), the build failed with LLVM/Clang:
```
/tmp/snort-20240220-4930-hdb526/snort3-3.1.81.0/tools/snort2lua/helpers/s2l_util.cc:106:74: error: no member named 'ptr_fun' in namespace 'std'
    s.erase(s.begin(), std::find_if(s.begin(), s.end(), std::not_fn(std::ptr_fun<int, int>(std::isspace))));
                                                                    ~~~~~^
```

This appears to be due to https://github.com/snort3/snort3/commit/b9be2f9a62c9e15e75bdf69fcf67566994d757a0 increasing C++ standard to C++17 but not replacing usage of `std::ptr_fun`:

https://github.com/snort3/snort3/blob/be0977a3a8a98632e5cd1238c1d0da6dc2693b5f/CMakeLists.txt#L14

https://github.com/snort3/snort3/blob/be0977a3a8a98632e5cd1238c1d0da6dc2693b5f/tools/snort2lua/helpers/s2l_util.cc#L106

`std::ptr_fun` is officially removed in C++17, ref: https://en.cppreference.com/w/cpp/utility/functional/ptr_fun

It looks like GCC may still allow usage of removed functions, but LLVM is stricter on this unless the `_LIBCPP_ENABLE_CXX17_REMOVED_BINDERS` macro is used, ref: https://libcxx.llvm.org/UsingLibcxx.html#c-17-specific-configuration-macros

**Comment by matirko** [comment]
This has been fixed and will show up in the next release. Thank you!
