### ISSUE TITLE
Build fails with OpenSSL 4.0 - const qualifiers and opaque ASN1_STRING

### ISSUE THREAD

**Issue by jaipaulcheernam** [snort3/snort3#476]
snort3 3.12.2.0 fails to build with OpenSSL 4.0.1.
  
  OpenSSL 4.0 returns `const` pointers from `X509_get_subject_name()`,
  `X509_NAME_get_entry()`, and `X509_NAME_ENTRY_get_data()`. The local
  variables in `src/protocols/ssl.cc` need const qualifiers to match.
  
  Errors:
  
  ssl.cc:878: error: invalid conversion from 'const X509_NAME*' to 'X509_NAME*'
  ssl.cc:879: error: invalid conversion from 'const X509_NAME*' to 'X509_NAME*'
  ssl.cc:921: error: invalid conversion from 'const X509_NAME_ENTRY*' to 'X509_NAME_ENTRY*'
  ssl.cc:922: error: invalid conversion from 'const ASN1_STRING*' to 'ASN1_STRING*'
  
  Fix is straightforward — add `const` to the local variable declarations.
  This is backward-compatible with older OpenSSL versions since assigning
  non-const to const is always valid.
  
  PR with fix: https://github.com/snort3/snort3/pull/477
