### ISSUE TITLE
 3.1.10.0 builds fine on FreeBSD 13, fails on FreeBSD 12.2 and 11.4 - unknown type name 'time_t'

### ISSUE THREAD

**Issue by dlangille** [snort3/snort3#210]
On both FreeBSD 12.2 and 11.4, building Snort 3.1.10.0 fails with these errors.  On FreeBSD 13, it builds just fine.

Attempts to debug this included patching the code to add includes of either or both of sys/time.h & sys/types.h - those patches failed to affect the outcome.

Partial log appears below.

Full logs are at:

- FreeBSD 11.4 : https://services.unixathome.org/poudriere/build.html?mastername=114R-dvl&build=2021-08-31_13h44m51s
- FreeBSD 12.2 : https://services.unixathome.org/poudriere/build.html?mastername=122amd64-dvl&build=2021-08-31_13h45m33s
- FreeBSD 13.0 : https://services.unixathome.org/poudriere/build.html?mastername=13amd64-dvl&build=2021-08-31_13h46m13s

```
In file included from /wrkdirs/usr/ports/security/snort3/work/snort3-3.1.10.0/src/control/control.cc:25:
/wrkdirs/usr/ports/security/snort3/work/snort3-3.1.10.0/src/control/control.h:54:5: error: unknown type name 'time_t'
    time_t get_touched() const;
    ^
/wrkdirs/usr/ports/security/snort3/work/snort3-3.1.10.0/src/control/control.h:78:5: error: unknown type name 'time_t'
    time_t touched;
    ^
2 errors generated.
```

**Comment by dlangille** [comment]
I regret to inform Snort 3.1.12.0 is also broken as described above.

Full build logs at:

* FreeBSD 11.4 - https://services.unixathome.org/poudriere/build.html?mastername=114R-dvl&build=2021-09-08_19h25m25s
* FreeBSD 12.2 - https://services.unixathome.org/poudriere/build.html?mastername=122amd64-dvl&build=2021-09-08_19h17m35s

**Comment by dlangille** [comment]
adding #include <ctime> to control.h fixed it

Next compile problem is

/wrkdirs/usr/ports/security/snort3/work/snort3-3.1.12.0/src/packet_io/sfdaq_instance.cc:393:17: error: use of undeclared identifier 'DAQ_EFLOW_BIDIRECTIONAL'
    if (flags & DAQ_EFLOW_BIDIRECTIONAL)

DAQ_EFLOW_BIDIRECTIONAL is not defined in the code for libdaq 3.0.4 - what's up with that?

**Comment by mjs717** [comment]
Yeah, the fix didn't make it into 3.1.12.0. I'd expect it to be in the next one. It's basically an include.

Grab the new DAQ release. You need 3.0.5.

**Comment by dlangille** [comment]
@mjs717 Thanks - I looked at https://snort.org/downloads and saw only 3.0.4 --- silly me.

**Comment by dlangille** [comment]
The patch to fix the build has been added to the FreeBSD ports tree: 

 * https://cgit.freebsd.org/ports/tree/security/snort3/files/patch-src_control_control.h

`snort3` & `libdaq` updated.

**Comment by mjs717** [comment]
Yeah, snort.org still has 3.1.10.0 published (with corresponding DAQ). 3.1.12.0 is staged and should be published tomorrow morning.

In general, it's probably best to just track either snort.org or github for everything together. The GitHub releases have to lead the snort.org publications (kind of by design).

**Comment by dlangille** [comment]
Thank you, yes, I should be following only Github. That is where FreeBSD pulls the tarballs from. I should have looked there first. :)

**Comment by Xiche** [comment]
Looks like the missing ctime include should have been resolved in e7a06f369a7f720bcedcd3d01e5c8b9b5beeecb4 - Is it working for you now, Dan?

**Comment by dlangille** [comment]
Yes, it is building now on FreeBSD 13.0 & 12.2 as well as 11.4 (which is now past EOL) - thank you.
